### ISSUE TITLE
Storage Miner Payments Epic

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1434]
It's time for clients to actually pay storage miners for storage.

- [ ] [Miner Price Setting](https://github.com/filecoin-project/go-filecoin/issues/1428)
- [ ] [Payment Channel Changes](https://github.com/filecoin-project/go-filecoin/issues/1429)
- [ ] [Clients manage their payment channels better](https://github.com/filecoin-project/go-filecoin/issues/1430)
- [ ] [Clients send valid payment channel vouchers](https://github.com/filecoin-project/go-filecoin/issues/1431)
- [ ] [Storage miners accept and validate payments](https://github.com/filecoin-project/go-filecoin/issues/1432)
- [ ] [Storage miners track received payment vouchers](https://github.com/filecoin-project/go-filecoin/issues/1433)

At the end of this epic, miners should actually be earning income for their provided storage. Filecoin will be one step closer to reality!

**Comment by mishmosh** [comment]
all 7 issues in this epic done, closing!

#1428
#1429
#1430
#1431
#1432
#1433
#1844
